### ISSUE TITLE
Samples talk about running docker example but docker-from-docker is not enabled.

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/ccf-app-template#13]
The readme.md talks about running the sample applications in a docker container. However Docker is not available from the devcontainer. You will receive a "Is docker daemon running?" message

**Comment by jumaffre** [comment]
Thank you for raising and fixing this. I believe the assumption of the existing `devcontainer.json` is that the docker daemon is installed on the host first (typically docker for Windows). Could you please confirm that you've tested the fix you've introduced on #14 as the CI wouldn't test this.

**Comment by ross-p-smith** [comment]
![image](https://user-images.githubusercontent.com/6254153/197585969-86a91811-3539-4275-84a8-54069f040796.png)
Here is a screen shot with my devcontainer and a terminal where I can now `docker images` and see the images using the host docker daemon.

As an aside - you can also use the devcontainer in your build if you would like me to put something together and show you?
