### ISSUE TITLE
CCF Apps with TPC-H SQL Queries?

### ISSUE THREAD

**Issue by Abida2024** [microsoft/ccf-app-template#23]
Hello, 

I'm not sure if this is the correct place to ask this, but what is the recommended way to go about serving SQL queries through a javascript or typescript CCF app? I would like to evaluate the performance of my ccf app using the standard tpc-h queries, but was just wondering if it would mess with any security guaranteed afforded by CCF?

**Comment by eddyashton** [comment]
Hi @Abida2024,

CCF communicates over HTTPS, and stores its data in a custom key-value store. To serve SQL queries, you would need to submit the query in a HTTP payload (ie - an off-the-shelf client that sends SQL directly to a DB over a custom wire protocol will not work), and then within the application code you'd need to run a SQL parser that could use the CCF KV as its backing datastore. So ideally you'd leverage an existing JS/TS library that could parse SQL, and included hooks to control reads/writes to the underlying data, at a granularity amenable to a key-value store. We believe this is viable, but haven't explored such a library before - there may be some difficulty in mapping a library's storage expectations (eg - expecting to write custom blobs to file) to a plain key-value store.

We have implemented the TPC-C benchmark in CCF ([source here](https://github.com/microsoft/CCF/tree/main/src/apps/tpcc)), and regularly run this in our performance testing.

Also just to note - it's fine to ask questions here (and GitHub notifications will bring them to our attention), but we're more active on the [main CCF repo](https://github.com/microsoft/ccf), and you may get a faster response there.

Hope this helps, please let me know if you have any more questions!

**Comment by eddyashton** [comment]
Ah I missed the final part of your question:

> wondering if it would mess with any security guaranteed afforded by CCF?

The simple answer is no - writing a CCF app that handles SQL will not break any security guarantees.

However, I think it's worth noting that an off-the-shelf benchmark like TPC-H, or a language like SQL, will not be able to make full use of the possible guarantees of CCF. Running them directly means the queries are confidentially executed, not visible to the host, and persisted to a ledger. With further modifications, we could get further benefits:
- To prove to a client that a request was executed correctly and confidentially, the client must process an attestation of the service's code
- To prove to a client that the request was persisted, and forms a single shared history with other executed requests, the client must process a signature from the service (ideally containing custom claims which bind it to the application content)
- To store confidential state for multiple parties, the requests must come from an authenticated identity, and the application must include some kind of access control. I believe (I'm no SQL expert!) that this is possible in some extensions/modifications, but not in core SQL
