### ISSUE TITLE
The link to create a codespace is broken

### ISSUE THREAD

**Issue by TheBankster** [microsoft/ccf-app-template#6]
The first link under "Quickstart" (https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=496290904&machine=basicLinux32gb&devcontainer_path=.devcontainer.json&location=WestEurope) gives a 404.

**Comment by jumaffre** [comment]
@TheBankster Thanks for raising this. I hadn't realised that GitHub codespaces were only available to users who were in organisations that pay to have them available. I've updated `README.md` with clearer instructions on how to build and run this app in a local development container. Could you give it a try and tell me if this is OK with your workflow?

**Comment by TheBankster** [comment]
Yes, this works much better. One other related request: under "Docker" section, can you provide instructions for how to start the container in virtual mode?

**Comment by jumaffre** [comment]
Good point. I'll add a virtual variant of the Dockerfile.

**Comment by TheBankster** [comment]
Thank you, closing this issue now.
